language: objective-c
osx_image: xcode8

before_install: 
- rvm use $RVM_RUBY_VERSION
- gem install slather --no-rdoc --no-ri --no-document --quiet

script:
- time ./travis/travis_build_script.sh

after_success: slather